# Generated by Django 5.2.7 on 2025-10-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("team", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TelemetryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_number", models.IntegerField()),
                ("lap_number", models.IntegerField()),
                ("lap_time", models.FloatField(null=True)),
                ("sector1_time", models.FloatField(null=True)),
                ("sector2_time", models.FloatField(null=True)),
                ("sector3_time", models.FloatField(null=True)),
                ("speed_trap", models.FloatField(null=True)),
                ("compound", models.CharField(max_length=20, null=True)),
                ("tyre_life", models.IntegerField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("round", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("circuit", models.CharField(max_length=200)),
                ("date", models.DateField()),
            ],
            options={
                "unique_together": {("season", "round")},
            },
        ),
    ]
