# Generated by Django 5.2.7 on 2025-10-25 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="race",
            options={"ordering": ["season", "round"]},
        ),
        migrations.AlterModelOptions(
            name="telemetrydata",
            options={"ordering": ["lap_number"]},
        ),
        migrations.AlterField(
            model_name="telemetrydata",
            name="compound",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="telemetrydata",
            name="lap_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="telemetrydata",
            name="sector1_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="telemetrydata",
            name="sector2_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="telemetrydata",
            name="sector3_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="telemetrydata",
            name="speed_trap",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="telemetrydata",
            name="tyre_life",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_type", models.CharField(max_length=20)),
                ("date", models.DateTimeField()),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="api.race",
                    ),
                ),
            ],
            options={
                "unique_together": {("race", "session_type")},
            },
        ),
        migrations.AddField(
            model_name="telemetrydata",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telemetry",
                to="api.session",
            ),
        ),
    ]
